name: logcat
description: Flutter plugin to get system messages, stack traces etc
version: 0.0.1
author: Harsh <pharsh.dev@gmail.com>
homepage: https://pharsh.dev

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: dev.pharsh.logcat
    pluginClass: LogcatPlugin
